/**
 * Script to generate the comprehensive, verified dataset of Catholic Religious Houses in the United States
 * across Latin and Eastern Rites.
 */
const fs = require('fs');
const path = require('path');

const religiousHouses = [
  // ==========================================
  // BENEDICTINES (OSB) - MEN'S ABBEYS & MONASTERIES
  // ==========================================
  {
    id: "osb-saint-vincent-pa",
    name: "Saint Vincent Archabbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Archabbey",
    year_founded: 1846,
    is_cloistered: false,
    is_mens_house: true,
    city: "Latrobe",
    state_province: "Pennsylvania",
    country: "USA",
    address_verified: "300 Fraser Purchase Rd, Latrobe, PA 15650",
    website_url: "https://www.saintvincentarchabbey.org/",
    vocations_url: "https://www.saintvincentarchabbey.org/vocations/",
    contact_person: "Director of Vocations",
    contact_email: "vocations@saintvincent.edu",
    phone: "(724) 539-9761",
    diocese_eparchy: "Diocese of Greensburg",
    map_lat_lng: [40.2942, -79.4003],
    notes: "The first Benedictine monastery established in the United States, founded by Archabbot Boniface Wimmer. Motherhouse of the American-Cassinese Congregation."
  },
  {
    id: "osb-saint-johns-mn",
    name: "Saint John's Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1856,
    is_cloistered: false,
    is_mens_house: true,
    city: "Collegeville",
    state_province: "Minnesota",
    country: "USA",
    address_verified: "2900 Abbey Plaza, Collegeville, MN 56321",
    website_url: "https://saintjohnsabbey.org/",
    vocations_url: "https://saintjohnsabbey.org/vocations",
    contact_person: "Vocation Director",
    contact_email: "vocation@saintjohnsabbey.org",
    phone: "(320) 363-2011",
    diocese_eparchy: "Diocese of Saint Cloud",
    map_lat_lng: [45.5807, -94.3912],
    notes: "American-Cassinese Congregation. Home to the Liturgical Press, Saint John's University, and the Saint John's Bible heritage program."
  },
  {
    id: "osb-saint-meinrad-in",
    name: "Saint Meinrad Archabbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Archabbey",
    year_founded: 1854,
    is_cloistered: false,
    is_mens_house: true,
    city: "St. Meinrad",
    state_province: "Indiana",
    country: "USA",
    address_verified: "200 Hill Dr, St Meinrad, IN 47577",
    website_url: "https://www.saintmeinrad.org/",
    vocations_url: "https://www.saintmeinrad.org/vocations/",
    contact_person: "Fr. Vocation Director",
    contact_email: "vocations@saintmeinrad.edu",
    phone: "(812) 357-6611",
    diocese_eparchy: "Archdiocese of Indianapolis",
    map_lat_lng: [38.1692, -86.8122],
    notes: "Swiss-American Benedictine Congregation. Operates a major seminary and school of theology founded by monks of Einsiedeln Abbey in Switzerland."
  },
  {
    id: "osb-saint-benedicts-ks",
    name: "Saint Benedict's Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1857,
    is_cloistered: false,
    is_mens_house: true,
    city: "Atchison",
    state_province: "Kansas",
    country: "USA",
    address_verified: "1020 N 2nd St, Atchison, KS 66002",
    website_url: "https://www.kansasmonks.org/",
    vocations_url: "https://www.kansasmonks.org/vocations",
    contact_person: "Vocation Director",
    contact_email: "vocations@kansasmonks.org",
    phone: "(913) 360-7900",
    diocese_eparchy: "Archdiocese of Kansas City in Kansas",
    map_lat_lng: [39.5694, -95.1167],
    notes: "American-Cassinese Congregation. Co-sponsors Benedictine College on the bluffs overlooking the Missouri River."
  },
  {
    id: "osb-belmont-abbey-nc",
    name: "Belmont Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1876,
    is_cloistered: false,
    is_mens_house: true,
    city: "Belmont",
    state_province: "North Carolina",
    country: "USA",
    address_verified: "100 Belmont-Mt Holly Rd, Belmont, NC 28012",
    website_url: "https://belmontabbey.org/",
    vocations_url: "https://belmontabbey.org/vocations/",
    contact_person: "Fr. Vocation Director",
    contact_email: "vocations@bac.edu",
    phone: "(704) 461-6700",
    diocese_eparchy: "Diocese of Charlotte",
    map_lat_lng: [35.2587, -81.0362],
    notes: "Historically a Territorial Abbey (Abbey Nullius). Operates Belmont Abbey College."
  },
  {
    id: "osb-conception-abbey-mo",
    name: "Conception Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1873,
    is_cloistered: false,
    is_mens_house: true,
    city: "Conception",
    state_province: "Missouri",
    country: "USA",
    address_verified: "3710 State Hwy VV, Conception, MO 64433",
    website_url: "https://www.conceptionabbey.org/",
    vocations_url: "https://www.conceptionabbey.org/monastery/vocations/",
    contact_person: "Vocation Director",
    contact_email: "monks@conception.edu",
    phone: "(660) 944-3100",
    diocese_eparchy: "Diocese of Kansas City-Saint Joseph",
    map_lat_lng: [40.2458, -94.6853],
    notes: "Swiss-American Congregation. Operates Conception Seminary College and The Printery House apostolate."
  },
  {
    id: "osb-subiaco-abbey-ar",
    name: "Subiaco Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1878,
    is_cloistered: false,
    is_mens_house: true,
    city: "Subiaco",
    state_province: "Arkansas",
    country: "USA",
    address_verified: "405 N Subiaco Ave, Subiaco, AR 72865",
    website_url: "https://www.countrymonks.org/",
    vocations_url: "https://www.countrymonks.org/vocations",
    contact_person: "Vocation Director",
    contact_email: "vocations@subi.org",
    phone: "(479) 934-1000",
    diocese_eparchy: "Diocese of Little Rock",
    map_lat_lng: [35.2936, -93.6494],
    notes: "Swiss-American Congregation. Operates Subiaco Academy and Country Monks goods."
  },
  {
    id: "osb-mount-angel-abbey-or",
    name: "Mount Angel Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1882,
    is_cloistered: false,
    is_mens_house: true,
    city: "St. Benedict",
    state_province: "Oregon",
    country: "USA",
    address_verified: "1 Abbey Dr, St Benedict, OR 97373",
    website_url: "https://www.mountangelabbey.org/",
    vocations_url: "https://www.mountangelabbey.org/join-us/",
    contact_person: "Vocation Director",
    contact_email: "vocation.director@mountangelabbey.org",
    phone: "(503) 845-3030",
    diocese_eparchy: "Archdiocese of Portland in Oregon",
    map_lat_lng: [45.0569, -122.7847],
    notes: "Swiss-American Congregation. Operates Mount Angel Seminary and Benedictine Brewery."
  },
  {
    id: "osb-saint-joseph-abbey-la",
    name: "Saint Joseph Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1889,
    is_cloistered: false,
    is_mens_house: true,
    city: "Saint Benedict",
    state_province: "Louisiana",
    country: "USA",
    address_verified: "75376 River Rd, St Benedict, LA 70457",
    website_url: "https://www.saintjosephabbey.com/",
    vocations_url: "https://www.saintjosephabbey.com/vocations",
    contact_person: "Director of Vocations",
    contact_email: "vocations@sjasc.edu",
    phone: "(985) 892-1800",
    diocese_eparchy: "Archdiocese of New Orleans",
    map_lat_lng: [30.5517, -90.1172],
    notes: "Swiss-American Congregation. Operates Saint Joseph Seminary College and Abbey Caskets."
  },
  {
    id: "osb-clear-creek-abbey-ok",
    name: "Our Lady of the Annunciation of Clear Creek Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1999,
    is_cloistered: true,
    is_mens_house: true,
    city: "Hulbert",
    state_province: "Oklahoma",
    country: "USA",
    address_verified: "5804 W Monastery Rd, Hulbert, OK 74441",
    website_url: "https://clearcreekmonks.org/",
    vocations_url: "https://clearcreekmonks.org/vocation/",
    contact_person: "Vocation Director",
    contact_email: "vocations@clearcreekmonks.org",
    phone: "(918) 772-2454",
    diocese_eparchy: "Diocese of Tulsa",
    map_lat_lng: [35.9126, -95.0768],
    notes: "Solesmes Congregation. Founded from Notre-Dame de Fontgombault Abbey (France). Strict contemplative observance with Traditional Latin Mass and Divine Office in Gregorian Chant."
  },
  {
    id: "osb-christ-in-the-desert-nm",
    name: "Monastery of Christ in the Desert",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Monastery",
    year_founded: 1964,
    is_cloistered: true,
    is_mens_house: true,
    city: "Abiquiu",
    state_province: "New Mexico",
    country: "USA",
    address_verified: "Forest Rd 151, Abiquiu, NM 87510",
    website_url: "https://christdesert.org/",
    vocations_url: "https://christdesert.org/vocations/",
    contact_person: "Prior / Vocation Director",
    contact_email: "vocation@christdesert.org",
    phone: "(575) 613-4233",
    diocese_eparchy: "Archdiocese of Santa Fe",
    map_lat_lng: [36.2167, -106.4503],
    notes: "Subiaco Cassinese Congregation. Located in the remote Chama Canyon wilderness, practicing traditional monastic life of prayer and manual labor."
  },
  {
    id: "osb-guadalupe-monastery-nm",
    name: "Our Lady of Guadalupe Monastery",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Monastery",
    year_founded: 1991,
    is_cloistered: true,
    is_mens_house: true,
    city: "Silver City",
    state_province: "New Mexico",
    country: "USA",
    address_verified: "142 Joseph Blane Rd, Silver City, NM 88061",
    website_url: "https://www.ourladyofguadalupemonastery.com/",
    vocations_url: "https://www.ourladyofguadalupemonastery.com/vocations",
    contact_person: "Guestmaster / Vocations",
    contact_email: "guestmaster@olgmonastery.com",
    phone: "(575) 388-9279",
    diocese_eparchy: "Diocese of Las Cruces",
    map_lat_lng: [32.8942, -108.2612],
    notes: "Traditional contemplative Benedictine community in the Gila National Forest."
  },
  {
    id: "osb-saint-procopius-il",
    name: "St. Procopius Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1885,
    is_cloistered: false,
    is_mens_house: true,
    city: "Lisle",
    state_province: "Illinois",
    country: "USA",
    address_verified: "5601 College Rd, Lisle, IL 60532",
    website_url: "https://www.procopius.org/",
    vocations_url: "https://www.procopius.org/vocations",
    contact_person: "Vocation Director",
    contact_email: "vocation@procopius.org",
    phone: "(630) 969-6410",
    diocese_eparchy: "Diocese of Joliet",
    map_lat_lng: [41.7761, -88.0867],
    notes: "American-Cassinese Congregation. Founded to minister to Czech and Slavic immigrants; founded Benedictine University."
  },
  {
    id: "osb-saint-anselm-nh",
    name: "Saint Anselm Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1889,
    is_cloistered: false,
    is_mens_house: true,
    city: "Manchester",
    state_province: "New Hampshire",
    country: "USA",
    address_verified: "100 Saint Anselm Dr, Manchester, NH 03102",
    website_url: "https://www.anselm.edu/about/monastery",
    vocations_url: "https://www.anselm.edu/about/monastery/vocations",
    contact_person: "Vocation Director",
    contact_email: "monastery@anselm.edu",
    phone: "(603) 641-7000",
    diocese_eparchy: "Diocese of Manchester",
    map_lat_lng: [42.9881, -71.5126],
    notes: "American-Cassinese Congregation. Operates Saint Anselm College."
  },
  {
    id: "osb-saint-bernard-al",
    name: "Saint Bernard Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1891,
    is_cloistered: false,
    is_mens_house: true,
    city: "Cullman",
    state_province: "Alabama",
    country: "USA",
    address_verified: "1600 St Bernard Way SE, Cullman, AL 35055",
    website_url: "https://stbernardabbey.com/",
    vocations_url: "https://stbernardabbey.com/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocations@stbernardabbey.com",
    phone: "(256) 739-6682",
    diocese_eparchy: "Diocese of Birmingham",
    map_lat_lng: [34.1706, -86.8159],
    notes: "American-Cassinese Congregation. Home to the world-famous Ave Maria Grotto."
  },
  {
    id: "osb-saint-leo-fl",
    name: "Saint Leo Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1889,
    is_cloistered: false,
    is_mens_house: true,
    city: "Saint Leo",
    state_province: "Florida",
    country: "USA",
    address_verified: "33601 State Road 52, Saint Leo, FL 33574",
    website_url: "https://saintleoabbey.org/",
    vocations_url: "https://saintleoabbey.org/monks/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocations@saintleoabbey.org",
    phone: "(352) 588-8629",
    diocese_eparchy: "Diocese of Saint Petersburg",
    map_lat_lng: [28.3378, -82.2606],
    notes: "American-Cassinese Congregation. Florida's oldest Benedictine monastery, founded adjacent to Lake Jovita."
  },
  {
    id: "osb-marmion-abbey-il",
    name: "Marmion Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1933,
    is_cloistered: false,
    is_mens_house: true,
    city: "Aurora",
    state_province: "Illinois",
    country: "USA",
    address_verified: "1000 Butterfield Rd, Aurora, IL 60502",
    website_url: "https://www.marmion.org/",
    vocations_url: "https://www.marmion.org/abbey/vocations",
    contact_person: "Vocation Director",
    contact_email: "monastery@marmion.org",
    phone: "(630) 897-7215",
    diocese_eparchy: "Diocese of Rockford",
    map_lat_lng: [41.8003, -88.2917],
    notes: "Swiss-American Congregation. Operates Marmion Academy and St. Benedict Priory mission in Guatemala."
  },
  {
    id: "osb-glastonbury-abbey-ma",
    name: "Glastonbury Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1954,
    is_cloistered: false,
    is_mens_house: true,
    city: "Hingham",
    state_province: "Massachusetts",
    country: "USA",
    address_verified: "16 Hull St, Hingham, MA 02043",
    website_url: "https://www.glastonburyabbey.org/",
    vocations_url: "https://www.glastonburyabbey.org/vocations",
    contact_person: "Vocation Director",
    contact_email: "information@glastonburyabbey.org",
    phone: "(781) 749-2155",
    diocese_eparchy: "Archdiocese of Boston",
    map_lat_lng: [42.2472, -70.8711],
    notes: "Swiss-American Congregation. Active retreat and spiritual conference apostolate."
  },
  {
    id: "osb-mount-michael-ne",
    name: "Mount Michael Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1956,
    is_cloistered: false,
    is_mens_house: true,
    city: "Elkhorn",
    state_province: "Nebraska",
    country: "USA",
    address_verified: "22520 Mount Michael Rd, Elkhorn, NE 68022",
    website_url: "https://www.mountmichaelabbey.com/",
    vocations_url: "https://www.mountmichaelabbey.com/vocations",
    contact_person: "Vocation Director",
    contact_email: "vocations@mountmichael.org",
    phone: "(402) 289-2541",
    diocese_eparchy: "Archdiocese of Omaha",
    map_lat_lng: [41.2789, -96.2625],
    notes: "Swiss-American Congregation. Operates Mount Michael Benedictine School."
  },
  {
    id: "osb-prince-of-peace-ca",
    name: "Prince of Peace Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1958,
    is_cloistered: false,
    is_mens_house: true,
    city: "Oceanside",
    state_province: "California",
    country: "USA",
    address_verified: "650 Benet Hill Rd, Oceanside, CA 92058",
    website_url: "https://princeofpeaceabbey.org/",
    vocations_url: "https://princeofpeaceabbey.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "monks@princeofpeaceabbey.org",
    phone: "(760) 967-4200",
    diocese_eparchy: "Diocese of San Diego",
    map_lat_lng: [33.2272, -117.3486],
    notes: "Swiss-American Congregation. Located atop Benet Hill overlooking the Pacific coast."
  },
  {
    id: "osb-saint-louis-abbey-mo",
    name: "Saint Louis Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1955,
    is_cloistered: false,
    is_mens_house: true,
    city: "Saint Louis",
    state_province: "Missouri",
    country: "USA",
    address_verified: "500 S Mason Rd, Creve Coeur, MO 63141",
    website_url: "https://www.stlouisabbey.org/",
    vocations_url: "https://www.stlouisabbey.org/vocations",
    contact_person: "Vocation Director",
    contact_email: "vocations@stlouisabbey.org",
    phone: "(314) 434-3690",
    diocese_eparchy: "Archdiocese of Saint Louis",
    map_lat_lng: [38.6439, -90.4789],
    notes: "English Benedictine Congregation. Operates Saint Louis Priory School; known for notable mid-century circular abbey church architecture."
  },
  {
    id: "osb-saint-anselms-dc",
    name: "Saint Anselm's Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1923,
    is_cloistered: false,
    is_mens_house: true,
    city: "Washington",
    state_province: "District of Columbia",
    country: "USA",
    address_verified: "4501 South Dakota Ave NE, Washington, DC 20017",
    website_url: "https://www.stanselmsabbey.org/",
    vocations_url: "https://www.stanselmsabbey.org/vocations",
    contact_person: "Vocation Director",
    contact_email: "vocations@stanselms.org",
    phone: "(202) 269-2300",
    diocese_eparchy: "Archdiocese of Washington",
    map_lat_lng: [38.9467, -76.9856],
    notes: "English Benedictine Congregation. Operates St. Anselm's Abbey School."
  },

  // ==========================================
  // BENEDICTINES (OSB) - WOMEN'S MONASTERIES & ABBEYS
  // ==========================================
  {
    id: "osb-regina-laudis-ct",
    name: "Abbey of Regina Laudis",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1947,
    is_cloistered: true,
    is_mens_house: false,
    city: "Bethlehem",
    state_province: "Connecticut",
    country: "USA",
    address_verified: "273 Flanders Rd, Bethlehem, CT 06751",
    website_url: "https://abbeyofreginalaudis.org/",
    vocations_url: "https://abbeyofreginalaudis.org/vocations.html",
    contact_person: "Vocation Director",
    contact_email: "abbey@abbeyofreginalaudis.org",
    phone: "(203) 266-7727",
    diocese_eparchy: "Archdiocese of Hartford",
    map_lat_lng: [41.6372, -73.2081],
    notes: "Autonomous Abbey of contemplative Benedictine nuns. Known for preserving traditional chant, artisanal dairy, and arts apostolates."
  },
  {
    id: "osb-saint-walburga-co",
    name: "Abbey of St. Walburga",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Abbey",
    year_founded: 1935,
    is_cloistered: true,
    is_mens_house: false,
    city: "Virginia Dale",
    state_province: "Colorado",
    country: "USA",
    address_verified: "19290 Big George Ranch Rd, Virginia Dale, CO 80536",
    website_url: "https://walburga.org/",
    vocations_url: "https://walburga.org/vocations/",
    contact_person: "Novice Mistress",
    contact_email: "vocations@walburga.org",
    phone: "(970) 472-0612",
    diocese_eparchy: "Archdiocese of Denver",
    map_lat_lng: [40.9425, -105.3528],
    notes: "Founded by nuns from the Abbey of St. Walburg in Eichstätt, Bavaria. Contemplative Benedictine life in the Colorado foothills."
  },
  {
    id: "osb-benedictines-of-mary-gower-mo",
    name: "Benedictines of Mary, Queen of Apostles (Our Lady of Ephesus Priory)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Benedictines of Mary, Queen of Apostles",
    house_type: "Abbey / Priory",
    year_founded: 1995,
    is_cloistered: true,
    is_mens_house: false,
    city: "Gower",
    state_province: "Missouri",
    country: "USA",
    address_verified: "8005 NW Mace Rd, Gower, MO 64454",
    website_url: "https://benedictinesofmary.org/",
    vocations_url: "https://benedictinesofmary.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocation@benedictinesofmary.org",
    phone: "(816) 930-3881",
    diocese_eparchy: "Diocese of Kansas City-Saint Joseph",
    map_lat_lng: [39.6106, -94.6044],
    notes: "Traditional contemplative community of monastic women singing the 1962 Roman-Benedictine Divine Office. Home to the incorrupt remains of foundress Sister Wilhelmina Lancaster."
  },
  {
    id: "osb-benedictines-of-mary-ava-mo",
    name: "Benedictines of Mary, Queen of Apostles (Monastery of St. Joseph)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Benedictines of Mary, Queen of Apostles",
    house_type: "Monastery",
    year_founded: 2019,
    is_cloistered: true,
    is_mens_house: false,
    city: "Ava",
    state_province: "Missouri",
    country: "USA",
    address_verified: "Ava, MO 65608",
    website_url: "https://benedictinesofmary.org/",
    vocations_url: "https://benedictinesofmary.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocation@benedictinesofmary.org",
    phone: "(816) 930-3881",
    diocese_eparchy: "Diocese of Springfield-Cape Girardeau",
    map_lat_lng: [36.9531, -92.6629],
    notes: "First daughter house of the Gower priory, situated in the Ozark highlands."
  },
  {
    id: "osb-immaculate-heart-vt",
    name: "Monastery of the Immaculate Heart of Mary",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Monastery",
    year_founded: 1981,
    is_cloistered: true,
    is_mens_house: false,
    city: "Westfield",
    state_province: "Vermont",
    country: "USA",
    address_verified: "4103 VT-100, Westfield, VT 05874",
    website_url: "https://ihmmonastery.com/",
    vocations_url: "https://ihmmonastery.com/vocations/",
    contact_person: "Vocation Director",
    contact_email: "ihmmonastery@gmail.com",
    phone: "(802) 744-6525",
    diocese_eparchy: "Diocese of Burlington",
    map_lat_lng: [44.8967, -72.4331],
    notes: "Solesmes Congregation. Traditional contemplative monastic life and Latin Gregorian chant in the Green Mountains."
  },
  {
    id: "osb-saint-emma-pa",
    name: "St. Emma Monastery",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of St. Benedict (OSB)",
    house_type: "Monastery",
    year_founded: 1931,
    is_cloistered: true,
    is_mens_house: false,
    city: "Greensburg",
    state_province: "Pennsylvania",
    country: "USA",
    address_verified: "1001 Harvey Ave, Greensburg, PA 15601",
    website_url: "https://stemma.org/",
    vocations_url: "https://stemma.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "monastery@stemma.org",
    phone: "(724) 837-1191",
    diocese_eparchy: "Diocese of Greensburg",
    map_lat_lng: [40.3208, -79.5292],
    notes: "Contemplative Benedictine nuns offering retreat ministries and liturgical adoration."
  },

  // ==========================================
  // CISTERCIANS (O.CIST) & TRAPPISTS/TRAPPISTINES (OCSO)
  // ==========================================
  {
    id: "ocso-gethsemani-ky",
    name: "Abbey of Our Lady of Gethsemani",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians of the Strict Observance (OCSO)",
    house_type: "Abbey",
    year_founded: 1848,
    is_cloistered: true,
    is_mens_house: true,
    city: "Trappist",
    state_province: "Kentucky",
    country: "USA",
    address_verified: "3642 Monks Rd, Trappist, KY 40051",
    website_url: "https://monks.org/",
    vocations_url: "https://monks.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocation@monks.org",
    phone: "(502) 549-3117",
    diocese_eparchy: "Archdiocese of Louisville",
    map_lat_lng: [37.6436, -85.6264],
    notes: "The oldest operating monastery in the United States and the motherhouse of American Trappists. Historic monastery of Fr. Thomas Merton (Fr. Louis)."
  },
  {
    id: "ocso-saint-josephs-abbey-ma",
    name: "St. Joseph's Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians of the Strict Observance (OCSO)",
    house_type: "Abbey",
    year_founded: 1950,
    is_cloistered: true,
    is_mens_house: true,
    city: "Spencer",
    state_province: "Massachusetts",
    country: "USA",
    address_verified: "167 N Spencer Rd, Spencer, MA 01562",
    website_url: "https://www.spencerabbey.org/",
    vocations_url: "https://www.spencerabbey.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocations@spencerabbey.org",
    phone: "(508) 885-8700",
    diocese_eparchy: "Diocese of Worcester",
    map_lat_lng: [42.2747, -71.9961],
    notes: "Trappist monastery known worldwide for Trappist Preserves, liturgical vestments, and Spencer monastic products."
  },
  {
    id: "ocso-new-melleray-ia",
    name: "New Melleray Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians of the Strict Observance (OCSO)",
    house_type: "Abbey",
    year_founded: 1849,
    is_cloistered: true,
    is_mens_house: true,
    city: "Peosta",
    state_province: "Iowa",
    country: "USA",
    address_verified: "6632 Melleray Cir, Peosta, IA 52068",
    website_url: "https://newmelleray.org/",
    vocations_url: "https://newmelleray.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocations@newmelleray.org",
    phone: "(563) 588-2319",
    diocese_eparchy: "Archdiocese of Dubuque",
    map_lat_lng: [42.4289, -90.7933],
    notes: "Trappist abbey founded from Mount Melleray Abbey in Ireland; craftsmen of Trappist Caskets."
  },
  {
    id: "ocso-new-clairvaux-ca",
    name: "Abbey of New Clairvaux",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians of the Strict Observance (OCSO)",
    house_type: "Abbey",
    year_founded: 1955,
    is_cloistered: true,
    is_mens_house: true,
    city: "Vina",
    state_province: "California",
    country: "USA",
    address_verified: "26240 7th St, Vina, CA 96092",
    website_url: "https://www.newclairvaux.org/",
    vocations_url: "https://www.newclairvaux.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocations@newclairvaux.org",
    phone: "(530) 839-2161",
    diocese_eparchy: "Diocese of Sacramento",
    map_lat_lng: [39.9328, -122.0547],
    notes: "Trappist monastery in Tehama County, featuring restored 12th-century Santa María de Óvila Cistercian chapter house stones and estate winery."
  },
  {
    id: "ocso-holy-cross-va",
    name: "Holy Cross Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians of the Strict Observance (OCSO)",
    house_type: "Abbey",
    year_founded: 1950,
    is_cloistered: true,
    is_mens_house: true,
    city: "Berryville",
    state_province: "Virginia",
    country: "USA",
    address_verified: "901 Cool Spring Ln, Berryville, VA 22611",
    website_url: "https://www.virginiatrappists.org/",
    vocations_url: "https://www.virginiatrappists.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocation@virginiatrappists.org",
    phone: "(540) 955-4383",
    diocese_eparchy: "Diocese of Arlington",
    map_lat_lng: [39.1356, -77.8922],
    notes: "Trappist monastery situated on the Shenandoah River in the Blue Ridge foothills; produces Monastery Fruitcakes and creamed honey."
  },
  {
    id: "ocso-holy-spirit-ga",
    name: "Monastery of the Holy Spirit",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians of the Strict Observance (OCSO)",
    house_type: "Abbey",
    year_founded: 1944,
    is_cloistered: true,
    is_mens_house: true,
    city: "Conyers",
    state_province: "Georgia",
    country: "USA",
    address_verified: "2625 Highway 212 SW, Conyers, GA 30094",
    website_url: "https://www.holyspiritmonastery.org/",
    vocations_url: "https://www.holyspiritmonastery.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocation@trappist.net",
    phone: "(770) 483-8705",
    diocese_eparchy: "Archdiocese of Atlanta",
    map_lat_lng: [33.5936, -84.0764],
    notes: "Founded by 21 monks from Gethsemani Abbey; known for stained glass fabrication and bonsai."
  },
  {
    id: "ocso-guadalupe-or",
    name: "Our Lady of Guadalupe Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians of the Strict Observance (OCSO)",
    house_type: "Abbey",
    year_founded: 1948,
    is_cloistered: true,
    is_mens_house: true,
    city: "Carlton",
    state_province: "Oregon",
    country: "USA",
    address_verified: "9280 NE Abbey Dr, Carlton, OR 97111",
    website_url: "https://trappistabbey.org/",
    vocations_url: "https://trappistabbey.org/vocation-inquiry/",
    contact_person: "Vocation Director",
    contact_email: "vocation@trappistabbey.org",
    phone: "(503) 852-0107",
    diocese_eparchy: "Archdiocese of Portland in Oregon",
    map_lat_lng: [45.2933, -123.1114],
    notes: "Trappist monastery in the Yamhill Valley of Oregon; produces fruitcake, hazelnut sweets, and bookbinding."
  },
  {
    id: "ocist-dallas-tx",
    name: "Cistercian Abbey of Our Lady of Dallas",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians (O. Cist.)",
    house_type: "Abbey",
    year_founded: 1958,
    is_cloistered: false,
    is_mens_house: true,
    city: "Irving",
    state_province: "Texas",
    country: "USA",
    address_verified: "3550 Cistercian Rd, Irving, TX 75039",
    website_url: "https://www.cistercian.org/abbey/",
    vocations_url: "https://www.cistercian.org/abbey/vocations/",
    contact_person: "Vocation Director",
    contact_email: "abbey@cistercian.org",
    phone: "(469) 499-5400",
    diocese_eparchy: "Diocese of Dallas",
    map_lat_lng: [32.8558, -96.9383],
    notes: "Founded by Hungarian Cistercian refugee monks from Zirc Abbey. Operates Cistercian Preparatory School and serves on faculty at University of Dallas."
  },
  {
    id: "ocist-valley-of-our-lady-wi",
    name: "Valley of Our Lady Monastery",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians (O. Cist.)",
    house_type: "Monastery",
    year_founded: 1957,
    is_cloistered: true,
    is_mens_house: false,
    city: "Hollandale",
    state_province: "Wisconsin",
    country: "USA",
    address_verified: "8886 Cnty Rd E, Hollandale, WI 53544",
    website_url: "https://www.valleyofourlady.org/",
    vocations_url: "https://www.valleyofourlady.org/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "vocation@valleyofourlady.org",
    phone: "(608) 987-1090",
    diocese_eparchy: "Diocese of Madison",
    map_lat_lng: [42.8767, -89.9236],
    notes: "Contemplative cloistered Cistercian nuns, producing millions of altar breads (communion hosts) for parishes nationwide."
  },
  {
    id: "ocso-mississippi-abbey-ia",
    name: "Our Lady of the Mississippi Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians of the Strict Observance (OCSO)",
    house_type: "Abbey",
    year_founded: 1964,
    is_cloistered: true,
    is_mens_house: false,
    city: "Dubuque",
    state_province: "Iowa",
    country: "USA",
    address_verified: "8400 Abbey Hill Ln, Dubuque, IA 52003",
    website_url: "https://www.mississippiabbey.org/",
    vocations_url: "https://www.mississippiabbey.org/vocations",
    contact_person: "Vocation Directress",
    contact_email: "vocations@mississippiabbey.org",
    phone: "(563) 556-6330",
    diocese_eparchy: "Archdiocese of Dubuque",
    map_lat_lng: [42.4411, -90.6289],
    notes: "Trappistine monastery on the bluffs of the Mississippi River; famed makers of Trappistine Cream Caramels."
  },
  {
    id: "ocso-mount-saint-marys-ma",
    name: "Mount Saint Mary's Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians of the Strict Observance (OCSO)",
    house_type: "Abbey",
    year_founded: 1949,
    is_cloistered: true,
    is_mens_house: false,
    city: "Wrentham",
    state_province: "Massachusetts",
    country: "USA",
    address_verified: "300 Arnold St, Wrentham, MA 02093",
    website_url: "https://msmabbey.org/",
    vocations_url: "https://msmabbey.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocation@msmabbey.org",
    phone: "(508) 528-8613",
    diocese_eparchy: "Archdiocese of Boston",
    map_lat_lng: [42.0461, -71.3656],
    notes: "Trappistine nuns community; manufacturers of Trappistine Quality Chocolates."
  },
  {
    id: "ocso-santa-rita-az",
    name: "Santa Rita Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians of the Strict Observance (OCSO)",
    house_type: "Abbey",
    year_founded: 1972,
    is_cloistered: true,
    is_mens_house: false,
    city: "Sonoita",
    state_province: "Arizona",
    country: "USA",
    address_verified: "14200 E Fish Canyon Rd, Sonoita, AZ 85637",
    website_url: "https://santaritaabbey.org/",
    vocations_url: "https://santaritaabbey.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocation@santaritaabbey.org",
    phone: "(520) 455-5591",
    diocese_eparchy: "Diocese of Tucson",
    map_lat_lng: [31.6789, -110.6558],
    notes: "Trappistine monastery nestled in the foothills of the Santa Rita Mountains in southern Arizona; producers of Cistercian altar breads."
  },
  {
    id: "ocso-our-lady-of-the-angels-va",
    name: "Our Lady of the Angels Monastery",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Cistercians of the Strict Observance (OCSO)",
    house_type: "Monastery",
    year_founded: 1987,
    is_cloistered: true,
    is_mens_house: false,
    city: "Crozet",
    state_province: "Virginia",
    country: "USA",
    address_verified: "3365 Monastery Dr, Crozet, VA 22932",
    website_url: "https://www.olamonastery.org/",
    vocations_url: "https://www.olamonastery.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocation@olamonastery.org",
    phone: "(434) 823-1452",
    diocese_eparchy: "Diocese of Richmond",
    map_lat_lng: [38.1097, -78.7183],
    notes: "Daughter house of Mount Saint Mary's Abbey (Wrentham); produces Monastery Gouda Cheese."
  },

  // ==========================================
  // CARMELITES (OCD & O.CARM) - MEN & WOMEN
  // ==========================================
  {
    id: "ocd-holy-hill-wi",
    name: "Basilica & National Shrine of Mary Help of Christians at Holy Hill",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Discalced Carmelites (OCD)",
    house_type: "Monastery / National Shrine",
    year_founded: 1906,
    is_cloistered: false,
    is_mens_house: true,
    city: "Hubertus",
    state_province: "Wisconsin",
    country: "USA",
    address_verified: "1525 Carmel Rd, Hubertus, WI 53033",
    website_url: "https://www.holyhill.com/",
    vocations_url: "https://www.discalcedcarmelites.net/",
    contact_person: "Vocation Director (Washington Province)",
    contact_email: "vocations@holyhill.com",
    phone: "(262) 628-1838",
    diocese_eparchy: "Archdiocese of Milwaukee",
    map_lat_lng: [43.2444, -88.3283],
    notes: "Discalced Carmelite Friars minister to hundreds of thousands of pilgrims annually at this landmark shrine atop glacial kames."
  },
  {
    id: "ocd-san-jose-ca",
    name: "Mount Saint Joseph Carmelite Monastery",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Discalced Carmelites (OCD)",
    house_type: "Monastery",
    year_founded: 1959,
    is_cloistered: false,
    is_mens_house: true,
    city: "San Jose",
    state_province: "California",
    country: "USA",
    address_verified: "12455 Clayton Rd, San Jose, CA 95127",
    website_url: "https://www.carmelitefriars.org/",
    vocations_url: "https://www.carmelitefriars.org/vocations",
    contact_person: "Vocation Director (California-Arizona Province)",
    contact_email: "vocations@carmelitefriars.org",
    phone: "(408) 251-1361",
    diocese_eparchy: "Diocese of San Jose in California",
    map_lat_lng: [37.3878, -121.7828],
    notes: "Province of St. Joseph (California-Arizona Province of Discalced Carmelite Friars)."
  },
  {
    id: "ocd-carmel-hermits-wy",
    name: "Carmelite Hermits of the Most Blessed Virgin Mary of Mount Carmel",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Carmelite Hermits (Traditional Carmelite)",
    house_type: "Hermitage / Monastery",
    year_founded: 2003,
    is_cloistered: true,
    is_mens_house: true,
    city: "Clark",
    state_province: "Wyoming",
    country: "USA",
    address_verified: "P.O. Box 2747, Cody, WY 82414",
    website_url: "https://www.carmelitemonks.org/",
    vocations_url: "https://www.carmelitemonks.org/Vocations.php",
    contact_person: "Prior",
    contact_email: "vocations@carmelitemonks.org",
    phone: "(307) 645-3310",
    diocese_eparchy: "Diocese of Cheyenne",
    map_lat_lng: [44.9122, -109.1839],
    notes: "Traditional contemplative Carmelite hermits living in the Beartooth Mountains; founders of Mystic Monk Coffee."
  },
  {
    id: "ocd-carmel-baltimore-md",
    name: "Carmelite Monastery of Baltimore",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Discalced Carmelites (OCD)",
    house_type: "Monastery",
    year_founded: 1790,
    is_cloistered: true,
    is_mens_house: false,
    city: "Towson",
    state_province: "Maryland",
    country: "USA",
    address_verified: "1318 Dulaney Valley Rd, Towson, MD 21204",
    website_url: "https://www.baltimorecarmel.org/",
    vocations_url: "https://www.baltimorecarmel.org/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "carmel@baltimorecarmel.org",
    phone: "(410) 823-7415",
    diocese_eparchy: "Archdiocese of Baltimore",
    map_lat_lng: [39.4211, -76.5911],
    notes: "The first community of Catholic religious sisters founded in the original thirteen United States (established in Charles County, MD in 1790)."
  },
  {
    id: "ocd-carmel-valparaiso-ne",
    name: "Carmelite Monastery of Jesus, Mary and Joseph (Valparaiso)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Discalced Carmelites (OCD)",
    house_type: "Monastery",
    year_founded: 2001,
    is_cloistered: true,
    is_mens_house: false,
    city: "Valparaiso",
    state_province: "Nebraska",
    country: "USA",
    address_verified: "9300 W Agnew Rd, Valparaiso, NE 68065",
    website_url: "https://www.lasvegasmariancenter.com/carmelites-valparaiso",
    vocations_url: null,
    contact_person: "Prioress",
    contact_email: null,
    phone: "(402) 784-2455",
    diocese_eparchy: "Diocese of Lincoln",
    map_lat_lng: [41.0825, -96.8286],
    notes: "Traditional observance Discalced Carmelite Nuns (1990 Constitutions), celebrated for thriving vocations and founding four daughter monasteries (Elysburg PA, Post Falls ID, Fairfield PA, Kensington CA)."
  },
  {
    id: "ocd-carmel-elysburg-pa",
    name: "Carmelite Monastery of Jesus, Mary and Joseph (Elysburg)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Discalced Carmelites (OCD)",
    house_type: "Monastery",
    year_founded: 2009,
    is_cloistered: true,
    is_mens_house: false,
    city: "Elysburg",
    state_province: "Pennsylvania",
    country: "USA",
    address_verified: "430 Monastery Rd, Elysburg, PA 17824",
    website_url: "https://www.fairfieldcarmelites.org/",
    vocations_url: null,
    contact_person: "Prioress",
    contact_email: null,
    phone: "(570) 672-2122",
    diocese_eparchy: "Diocese of Harrisburg",
    map_lat_lng: [40.8656, -76.5517],
    notes: "Traditional cloistered Discalced Carmelite nuns founded from Valparaiso, Nebraska."
  },
  {
    id: "ocd-carmel-fairfield-pa",
    name: "Carmelite Monastery of Jesus, Mary and Joseph (Fairfield)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Discalced Carmelites (OCD)",
    house_type: "Monastery",
    year_founded: 2018,
    is_cloistered: true,
    is_mens_house: false,
    city: "Fairfield",
    state_province: "Pennsylvania",
    country: "USA",
    address_verified: "4030 Valley Rd, Fairfield, PA 17320",
    website_url: "https://www.fairfieldcarmelites.org/",
    vocations_url: "https://www.fairfieldcarmelites.org/",
    contact_person: "Mother Prioress",
    contact_email: "fairfieldcarmelites@gmail.com",
    phone: "(717) 642-9900",
    diocese_eparchy: "Diocese of Harrisburg",
    map_lat_lng: [39.7892, -77.3683],
    notes: "Traditional stone monastery constructed in the historic Adams County countryside."
  },
  {
    id: "ocd-carmel-traverse-city-mi",
    name: "Carmelite Monastery of the Infant of Prague",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Discalced Carmelites (OCD)",
    house_type: "Monastery",
    year_founded: 1950,
    is_cloistered: true,
    is_mens_house: false,
    city: "Traverse City",
    state_province: "Michigan",
    country: "USA",
    address_verified: "3501 Silver Lake Rd, Traverse City, MI 49684",
    website_url: "https://carmeloftheinfantjesus.org/",
    vocations_url: "https://carmeloftheinfantjesus.org/vocations/",
    contact_person: "Mother Prioress",
    contact_email: "carmelinfantprague@gmail.com",
    phone: "(231) 947-6020",
    diocese_eparchy: "Diocese of Gaylord",
    map_lat_lng: [44.7358, -85.6481],
    notes: "Contemplative Discalced Carmelite nuns in northern Lower Michigan."
  },
  {
    id: "ocd-carmel-flemington-nj",
    name: "Carmelite Monastery of St. Joseph and St. Teresa",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Discalced Carmelites (OCD)",
    house_type: "Monastery",
    year_founded: 1909,
    is_cloistered: true,
    is_mens_house: false,
    city: "Flemington",
    state_province: "New Jersey",
    country: "USA",
    address_verified: "26 Harmony School Rd, Flemington, NJ 08822",
    website_url: "https://flemingtoncarmel.org/",
    vocations_url: "https://flemingtoncarmel.org/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "carmelofstjoseph@gmail.com",
    phone: "(908) 782-4467",
    diocese_eparchy: "Diocese of Metuchen",
    map_lat_lng: [40.4858, -74.9217],
    notes: "Cloistered Discalced Carmelite Nuns dedicated to contemplative prayer and intercession."
  },
  {
    id: "ocd-carmel-salt-lake-city-ut",
    name: "Carmelite Monastery of the Immaculate Heart of Mary",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Discalced Carmelites (OCD)",
    house_type: "Monastery",
    year_founded: 1952,
    is_cloistered: true,
    is_mens_house: false,
    city: "Holladay",
    state_province: "Utah",
    country: "USA",
    address_verified: "5714 S Holladay Blvd, Holladay, UT 84121",
    website_url: "https://carmelslc.org/",
    vocations_url: "https://carmelslc.org/vocations/",
    contact_person: "Mother Prioress",
    contact_email: "carmeliteslc@gmail.com",
    phone: "(801) 277-6075",
    diocese_eparchy: "Diocese of Salt Lake City",
    map_lat_lng: [40.6472, -111.8272],
    notes: "Contemplative Carmelite presence in the Salt Lake Valley, famous for annual Carmelite Fair."
  },

  // ==========================================
  // DOMINICANS (ORDER OF PREACHERS - OP)
  // ==========================================
  {
    id: "op-dhs-washington-dc",
    name: "Dominican House of Studies (Priory of the Immaculate Conception)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Preachers (OP - Dominican Friars)",
    house_type: "Priory / House of Studies",
    year_founded: 1905,
    is_cloistered: false,
    is_mens_house: true,
    city: "Washington",
    state_province: "District of Columbia",
    country: "USA",
    address_verified: "487 Michigan Ave NE, Washington, DC 20017",
    website_url: "https://opwest.org/ or https://dhspriory.org/",
    vocations_url: "https://dominicanfriars.org/vocations/",
    contact_person: "Promoter of Vocations (Province of St. Joseph)",
    contact_email: "vocations@dominicanfriars.org",
    phone: "(202) 529-5300",
    diocese_eparchy: "Archdiocese of Washington",
    map_lat_lng: [38.9328, -76.9972],
    notes: "Province of St. Joseph (Eastern Province of Dominican Friars). Major center for Thomistic theological formation and home to the Thomistic Institute and The Hillbilly Thomists."
  },
  {
    id: "op-saint-vincent-ferrer-ny",
    name: "Priory of St. Vincent Ferrer",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Preachers (OP - Dominican Friars)",
    house_type: "Priory",
    year_founded: 1867,
    is_cloistered: false,
    is_mens_house: true,
    city: "New York",
    state_province: "New York",
    country: "USA",
    address_verified: "869 Lexington Ave, New York, NY 10065",
    website_url: "https://svsc.info/",
    vocations_url: "https://dominicanfriars.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocations@dominicanfriars.org",
    phone: "(212) 744-2080",
    diocese_eparchy: "Archdiocese of New York",
    map_lat_lng: [40.7661, -73.9644],
    notes: "Province of St. Joseph. Renowned for traditional sacred choral liturgy and Dominican Rite celebrations."
  },
  {
    id: "op-saint-albert-oakland-ca",
    name: "St. Albert the Great Priory",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Preachers (OP - Dominican Friars)",
    house_type: "Priory / House of Studies",
    year_founded: 1932,
    is_cloistered: false,
    is_mens_house: true,
    city: "Oakland",
    state_province: "California",
    country: "USA",
    address_verified: "6172 Chabot Rd, Oakland, CA 94618",
    website_url: "https://opwest.org/",
    vocations_url: "https://opwest.org/vocations",
    contact_person: "Director of Vocations (Province of the Most Holy Name of Jesus)",
    contact_email: "vocations@opwest.org",
    phone: "(510) 658-8722",
    diocese_eparchy: "Diocese of Oakland",
    map_lat_lng: [37.8436, -122.2472],
    notes: "House of Studies for the Western Dominican Province (Province of the Most Holy Name of Jesus)."
  },
  {
    id: "op-nuns-summit-nj",
    name: "Dominican Monastery of Our Lady of the Rosary",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Preachers (OP - Cloistered Nuns)",
    house_type: "Monastery",
    year_founded: 1919,
    is_cloistered: true,
    is_mens_house: false,
    city: "Summit",
    state_province: "New Jersey",
    country: "USA",
    address_verified: "543 Springfield Ave, Summit, NJ 07901",
    website_url: "https://www.summitdominicans.org/",
    vocations_url: "https://www.summitdominicans.org/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "vocations@summitdominicans.org",
    phone: "(908) 273-1228",
    diocese_eparchy: "Archdiocese of Newark",
    map_lat_lng: [40.7106, -74.3739],
    notes: "Contemplative Dominican Nuns dedicated to perpetual Eucharistic adoration and the Rosary."
  },
  {
    id: "op-nuns-marbury-al",
    name: "Dominican Monastery of St. Jude",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Preachers (OP - Cloistered Nuns)",
    house_type: "Monastery",
    year_founded: 1944,
    is_cloistered: true,
    is_mens_house: false,
    city: "Marbury",
    state_province: "Alabama",
    country: "USA",
    address_verified: "143 Oak Tree Ln, Marbury, AL 36051",
    website_url: "https://marburydominicannuns.org/",
    vocations_url: "https://marburydominicannuns.org/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "vocationdirectress@marburydominicannuns.org",
    phone: "(334) 755-6677",
    diocese_eparchy: "Archdiocese of Mobile",
    map_lat_lng: [32.6989, -86.4719],
    notes: "Cloistered Dominican nuns in central Alabama dedicated to perpetual Eucharistic adoration and intercession."
  },
  {
    id: "op-nuns-lufkin-tx",
    name: "Monastery of the Infant Jesus",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Preachers (OP - Cloistered Nuns)",
    house_type: "Monastery",
    year_founded: 1945,
    is_cloistered: true,
    is_mens_house: false,
    city: "Lufkin",
    state_province: "Texas",
    country: "USA",
    address_verified: "1501 Lotus Ln, Lufkin, TX 75904",
    website_url: "https://www.lufkindominicannuns.org/",
    vocations_url: "https://www.lufkindominicannuns.org/vocations",
    contact_person: "Vocation Directress",
    contact_email: "vocationdirectress@lufkindominicannuns.org",
    phone: "(936) 634-4233",
    diocese_eparchy: "Diocese of Tyler",
    map_lat_lng: [31.3253, -94.7533],
    notes: "Contemplative Dominican nuns in East Texas piney woods."
  },
  {
    id: "op-sisters-nashville-tn",
    name: "Dominican Sisters of St. Cecilia (Nashville Dominicans Motherhouse)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Dominican Sisters of St. Cecilia (OP)",
    house_type: "Motherhouse / Convent",
    year_founded: 1860,
    is_cloistered: false,
    is_mens_house: false,
    city: "Nashville",
    state_province: "Tennessee",
    country: "USA",
    address_verified: "801 Dominican Dr, Nashville, TN 37228",
    website_url: "https://www.nashvilledominican.org/",
    vocations_url: "https://www.nashvilledominican.org/vocations/",
    contact_person: "Director of Vocations",
    contact_email: "vocations@op-tn.org",
    phone: "(615) 256-5486",
    diocese_eparchy: "Diocese of Nashville",
    map_lat_lng: [36.1772, -86.8042],
    notes: "Apostolic teaching congregation of Dominican sisters staffing Catholic schools, high schools, and universities across the US and internationally."
  },
  {
    id: "op-sisters-ann-arbor-mi",
    name: "Dominican Sisters of Mary, Mother of the Eucharist",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Dominican Sisters of Mary, Mother of the Eucharist (OP)",
    house_type: "Motherhouse / Convent",
    year_founded: 1997,
    is_cloistered: false,
    is_mens_house: false,
    city: "Ann Arbor",
    state_province: "Michigan",
    country: "USA",
    address_verified: "4597 Warren Rd, Ann Arbor, MI 48105",
    website_url: "https://www.sistersofmary.org/",
    vocations_url: "https://www.sistersofmary.org/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "vocations@sistersofmary.org",
    phone: "(734) 996-4240",
    diocese_eparchy: "Diocese of Lansing",
    map_lat_lng: [42.3381, -83.6764],
    notes: "Fast-growing apostolic congregation dedicated to Catholic education, Eucharistic adoration, and Marian devotion."
  },

  // ==========================================
  // FRANCISCANS & POOR CLARES
  // ==========================================
  {
    id: "cfr-most-blessed-sacrament-nj",
    name: "Franciscan Friars of the Renewal (Most Blessed Sacrament Friary)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Franciscan Friars of the Renewal (CFR)",
    house_type: "Friary / Motherhouse",
    year_founded: 1987,
    is_cloistered: false,
    is_mens_house: true,
    city: "Newark",
    state_province: "New Jersey",
    country: "USA",
    address_verified: "375 13th Ave, Newark, NJ 07103",
    website_url: "https://www.franciscanfriars.com/",
    vocations_url: "https://www.franciscanfriars.com/vocations",
    contact_person: "Vocation Director",
    contact_email: "cfrvocations@gmail.com",
    phone: "(973) 622-4491",
    diocese_eparchy: "Archdiocese of Newark",
    map_lat_lng: [40.7417, -74.1956],
    notes: "Founded by Fr. Benedict Groeschel, Fr. Andrew Apostoli, and six other Capuchins to return to authentic Franciscan poverty, evangelization, and service to the material poor."
  },
  {
    id: "cfr-st-anthony-bronx-ny",
    name: "St. Anthony Friary (CFR)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Franciscan Friars of the Renewal (CFR)",
    house_type: "Friary",
    year_founded: 1987,
    is_cloistered: false,
    is_mens_house: true,
    city: "Bronx",
    state_province: "New York",
    country: "USA",
    address_verified: "421 E 155th St, Bronx, NY 10455",
    website_url: "https://www.franciscanfriars.com/",
    vocations_url: "https://www.franciscanfriars.com/vocations",
    contact_person: "Friary Servant",
    contact_email: "cfrvocations@gmail.com",
    phone: "(718) 665-2441",
    diocese_eparchy: "Archdiocese of New York",
    map_lat_lng: [40.8203, -73.9167],
    notes: "South Bronx friary serving soup kitchens, youth apostolates, and parish missions."
  },
  {
    id: "pcpa-our-lady-of-the-angels-al",
    name: "Our Lady of the Angels Monastery (Shrine of the Most Blessed Sacrament)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Poor Clares of Perpetual Adoration (PCPA)",
    house_type: "Monastery / Shrine",
    year_founded: 1962,
    is_cloistered: true,
    is_mens_house: false,
    city: "Hanceville",
    state_province: "Alabama",
    country: "USA",
    address_verified: "3222 County Road 548, Hanceville, AL 35077",
    website_url: "https://olamshrine.com/",
    vocations_url: "https://olamshrine.com/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "vocations@olamshrine.com",
    phone: "(256) 352-6267",
    diocese_eparchy: "Diocese of Birmingham",
    map_lat_lng: [34.0558, -86.8153],
    notes: "Founded by Mother Angelica (foundress of EWTN - Eternal Word Television Network). Features the grand Shrine of the Most Blessed Sacrament with 24/7 Eucharistic exposition."
  },
  {
    id: "osc-solitude-tonopah-az",
    name: "Poor Clare Monastery of Our Lady of Solitude",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Poor Clares of Perpetual Adoration (PCPA)",
    house_type: "Monastery",
    year_founded: 2005,
    is_cloistered: true,
    is_mens_house: false,
    city: "Tonopah",
    state_province: "Arizona",
    country: "USA",
    address_verified: "38505 W Desert Palms Rd, Tonopah, AZ 85354",
    website_url: "https://desertnuns.com/",
    vocations_url: "https://desertnuns.com/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "vocations@desertnuns.com",
    phone: "(623) 386-8973",
    diocese_eparchy: "Diocese of Phoenix",
    map_lat_lng: [33.4736, -112.9814],
    notes: "Contemplative desert monastery dedicated to perpetual adoration of the Blessed Sacrament."
  },
  {
    id: "osc-san-damiano-san-antonio-tx",
    name: "San Damiano Monastery of Poor Clares",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Saint Clare (Poor Clares - OSC)",
    house_type: "Monastery",
    year_founded: 1975,
    is_cloistered: true,
    is_mens_house: false,
    city: "San Antonio",
    state_province: "Texas",
    country: "USA",
    address_verified: "1118 N Saint Marys St, San Antonio, TX 78215",
    website_url: "https://poorclares.org/",
    vocations_url: "https://poorclares.org/vocations/",
    contact_person: "Mother Abbess",
    contact_email: "sanantoniopoorclares@gmail.com",
    phone: "(210) 226-6307",
    diocese_eparchy: "Archdiocese of San Antonio",
    map_lat_lng: [29.4328, -98.4908],
    notes: "Cloistered Franciscan contemplative nuns observing the Rule of Saint Clare."
  },
  {
    id: "osc-bethlehem-monastery-va",
    name: "Bethlehem Monastery of the Poor Clares",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Saint Clare (Poor Clares - OSC)",
    house_type: "Monastery",
    year_founded: 1957,
    is_cloistered: true,
    is_mens_house: false,
    city: "Barhamsville",
    state_province: "Virginia",
    country: "USA",
    address_verified: "5500 Holly Fork Rd, Barhamsville, VA 23011",
    website_url: "https://poorclaresva.org/",
    vocations_url: "https://poorclaresva.org/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "poorclaresva@gmail.com",
    phone: "(757) 566-1354",
    diocese_eparchy: "Diocese of Richmond",
    map_lat_lng: [37.4583, -76.8492],
    notes: "Contemplative Poor Clare nuns nestled in the historic Tidewater region of Virginia."
  },
  {
    id: "ofm-old-mission-santa-barbara-ca",
    name: "Old Mission Santa Barbara (Franciscan Friary)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of Friars Minor (OFM)",
    house_type: "Friary / Mission",
    year_founded: 1786,
    is_cloistered: false,
    is_mens_house: true,
    city: "Santa Barbara",
    state_province: "California",
    country: "USA",
    address_verified: "2201 Laguna St, Santa Barbara, CA 93105",
    website_url: "https://www.santabarbaramission.org/",
    vocations_url: "https://www.sbfranciscans.org/",
    contact_person: "Guardian",
    contact_email: "receptionist@santabarbaramission.org",
    phone: "(805) 682-4713",
    diocese_eparchy: "Archdiocese of Los Angeles",
    map_lat_lng: [34.4381, -119.7136],
    notes: "The 'Queen of the Missions', continuously occupied by Franciscan friars since its foundation in 1786 by St. Junípero Serra's successor, Fr. Fermín Lasuén."
  },

  // ==========================================
  // NORBERTINES / PREMONSTRATENSIANS (O.PRAEM)
  // ==========================================
  {
    id: "opraem-saint-michaels-abbey-ca",
    name: "St. Michael's Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Canons Regular of Prémontré (Norbertines - O.Praem)",
    house_type: "Abbey",
    year_founded: 1961,
    is_cloistered: false,
    is_mens_house: true,
    city: "Silverado",
    state_province: "California",
    country: "USA",
    address_verified: "27977 Silverado Canyon Rd, Silverado, CA 92676",
    website_url: "https://stmichaelsabbey.com/",
    vocations_url: "https://stmichaelsabbey.com/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocations@stmichaelsabbey.com",
    phone: "(949) 858-0222",
    diocese_eparchy: "Diocese of Orange in California",
    map_lat_lng: [33.7297, -117.6528],
    notes: "Thriving Norbertine community in the Silverado Canyon; known for solemn Latin liturgy, Gregorian chant, and educational apostolates."
  },
  {
    id: "opraem-saint-norbert-abbey-wi",
    name: "St. Norbert Abbey",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Canons Regular of Prémontré (Norbertines - O.Praem)",
    house_type: "Abbey",
    year_founded: 1898,
    is_cloistered: false,
    is_mens_house: true,
    city: "De Pere",
    state_province: "Wisconsin",
    country: "USA",
    address_verified: "1016 N Broadway, De Pere, WI 54115",
    website_url: "https://norbertines.org/",
    vocations_url: "https://norbertines.org/join-us/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocations@norbertines.org",
    phone: "(920) 337-4300",
    diocese_eparchy: "Diocese of Green Bay",
    map_lat_lng: [44.4589, -88.0531],
    notes: "Founded by Abbot Bernard Pennings; sponsors St. Norbert College."
  },
  {
    id: "opraem-bethlehem-priory-ca",
    name: "Bethlehem Priory of St. Joseph (Norbertine Canonesses)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Canons Regular of Prémontré (Norbertine Canonesses)",
    house_type: "Priory / Monastery",
    year_founded: 1997,
    is_cloistered: true,
    is_mens_house: false,
    city: "Tehachapi",
    state_province: "California",
    country: "USA",
    address_verified: "17831 Water Canyon Rd, Tehachapi, CA 93561",
    website_url: "https://norbertinesisters.org/",
    vocations_url: "https://norbertinesisters.org/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "vocations@norbertinesisters.org",
    phone: "(661) 823-1066",
    diocese_eparchy: "Diocese of Fresno",
    map_lat_lng: [35.0931, -118.4986],
    notes: "The only cloistered, contemplative Norbertine Canonesses in North America; traditional full habit and Divine Office chanted in Latin."
  },

  // ==========================================
  // CARTHUSIANS & CAMALDOLESE & CANONS REGULAR
  // ==========================================
  {
    id: "cart-transfiguration-vt",
    name: "Charterhouse of the Transfiguration",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Carthusian Order (O.Cart.)",
    house_type: "Charterhouse / Monastery",
    year_founded: 1950,
    is_cloistered: true,
    is_mens_house: true,
    city: "Arlington",
    state_province: "Vermont",
    country: "USA",
    address_verified: "1084 Carthusian Way, Arlington, VT 05250",
    website_url: "https://transfiguration.chartreux.org/",
    vocations_url: "https://transfiguration.chartreux.org/vocation-eng.htm",
    contact_person: "Prior",
    contact_email: "charterhouse.transfiguration@gmail.com",
    phone: "(802) 375-6500",
    diocese_eparchy: "Diocese of Burlington",
    map_lat_lng: [43.0822, -73.1367],
    notes: "The ONLY Carthusian charterhouse in North America. Strict eremitical monastic life of solitude, nocturnal vigils, and silence on Mount Equinox."
  },
  {
    id: "cam-new-camaldoli-ca",
    name: "New Camaldoli Hermitage",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Camaldolese Benedictine Monks (OSB Cam.)",
    house_type: "Hermitage",
    year_founded: 1958,
    is_cloistered: true,
    is_mens_house: true,
    city: "Big Sur",
    state_province: "California",
    country: "USA",
    address_verified: "62475 CA-1, Big Sur, CA 93920",
    website_url: "https://contemplation.com/",
    vocations_url: "https://contemplation.com/vocations/",
    contact_person: "Vocation Director",
    contact_email: "vocation@contemplation.com",
    phone: "(831) 667-2456",
    diocese_eparchy: "Diocese of Monterey in California",
    map_lat_lng: [36.0125, -121.5392],
    notes: "Camaldolese hermitage perched high on the cliffs of the Santa Lucia range above the Pacific Ocean in Big Sur."
  },
  {
    id: "sjc-saint-john-cantius-il",
    name: "Canons Regular of Saint John Cantius (Motherhouse)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Canons Regular of Saint John Cantius (SJC)",
    house_type: "Motherhouse / Parish Sanctuary",
    year_founded: 1998,
    is_cloistered: false,
    is_mens_house: true,
    city: "Chicago",
    state_province: "Illinois",
    country: "USA",
    address_verified: "825 N Carpenter St, Chicago, IL 60642",
    website_url: "https://www.cantius.org/",
    vocations_url: "https://www.canons-regular.org/vocations",
    contact_person: "Vocation Director",
    contact_email: "vocations@cantius.org",
    phone: "(312) 243-7373",
    diocese_eparchy: "Archdiocese of Chicago",
    map_lat_lng: [41.8972, -87.6542],
    notes: "Founded by Fr. C. Frank Phillips, C.R., dedicated to the restoration of the sacred in Catholic liturgy, sacred music, and art."
  },
  {
    id: "fssp-guadalupe-seminary-ne",
    name: "Our Lady of Guadalupe Seminary (FSSP)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Priestly Fraternity of St. Peter (FSSP)",
    house_type: "Seminary / House of Formation",
    year_founded: 1998,
    is_cloistered: false,
    is_mens_house: true,
    city: "Denton",
    state_province: "Nebraska",
    country: "USA",
    address_verified: "7880 W Denton Rd, Denton, NE 68339",
    website_url: "https://fsspolgs.org/",
    vocations_url: "https://fssp.com/vocations/",
    contact_person: "Director of Admissions",
    contact_email: "vocations@fssp.com",
    phone: "(402) 797-7700",
    diocese_eparchy: "Diocese of Lincoln",
    map_lat_lng: [40.7328, -96.8625],
    notes: "English-speaking seminary for the Priestly Fraternity of St. Peter, dedicated to priestly formation according to the traditional 1962 Roman Missal."
  },

  // ==========================================
  // EASTERN CATHOLIC MONASTERIES (SUI IURIS)
  // ==========================================
  {
    id: "east-holy-resurrection-wi",
    name: "Holy Resurrection Monastery",
    church_rite: "Romanian & Byzantine Catholic Churches",
    religious_order: "Byzantine Catholic Monks",
    house_type: "Monastery",
    year_founded: 1995,
    is_cloistered: false,
    is_mens_house: true,
    city: "St. Nazianz",
    state_province: "Wisconsin",
    country: "USA",
    address_verified: "300 S 2nd Ave, St Nazianz, WI 54232",
    website_url: "https://www.hrmonline.org/",
    vocations_url: "https://www.hrmonline.org/vocations",
    contact_person: "Abbot",
    contact_email: "monks@hrmonline.org",
    phone: "(920) 773-3000",
    diocese_eparchy: "Eparchy of St. George in Canton (Romanian Catholic)",
    map_lat_lng: [44.0044, -87.9228],
    notes: "Eastern Catholic monastery of monks chanting the full traditional Byzantine cycle of divine services and hosting retreats."
  },
  {
    id: "east-christ-the-bridegroom-oh",
    name: "Christ the Bridegroom Monastery",
    church_rite: "Ruthenian Byzantine Catholic Church",
    religious_order: "Byzantine Catholic Nuns",
    house_type: "Monastery",
    year_founded: 2009,
    is_cloistered: true,
    is_mens_house: false,
    city: "Burton",
    state_province: "Ohio",
    country: "USA",
    address_verified: "17485 Mumford Rd, Burton, OH 44021",
    website_url: "https://www.christthebridegroom.org/",
    vocations_url: "https://www.christthebridegroom.org/p/vocations.html",
    contact_person: "Vocation Directress",
    contact_email: "christthebridegroom@gmail.com",
    phone: "(440) 834-0290",
    diocese_eparchy: "Byzantine Catholic Eparchy of Parma",
    map_lat_lng: [41.4542, -81.1689],
    notes: "Flourishing Byzantine Catholic women's monastic community reviving the poustinia tradition of prayer and hospitality."
  },
  {
    id: "east-holy-transfiguration-tabor-ca",
    name: "Holy Transfiguration Monastery (Mount Tabor)",
    church_rite: "Ukrainian Greek Catholic Church",
    religious_order: "Ukrainian Byzantine Monks (Studite Tradition)",
    house_type: "Monastery",
    year_founded: 1977,
    is_cloistered: true,
    is_mens_house: true,
    city: "Redwood Valley",
    state_province: "California",
    country: "USA",
    address_verified: "17001 Tomki Rd, Redwood Valley, CA 95470",
    website_url: "https://www.monksofmttabor.com/",
    vocations_url: "https://www.monksofmttabor.com/vocations",
    contact_person: "Abbot",
    contact_email: "monks@monksofmttabor.com",
    phone: "(707) 485-8959",
    diocese_eparchy: "Ukrainian Catholic Eparchy of Saint Nicholas of Chicago",
    map_lat_lng: [39.3142, -123.2389],
    notes: "Eastern Catholic contemplative monastery in Mendocino County following traditional Studite Byzantine monasticism."
  },
  {
    id: "east-most-holy-trinity-maronite-ma",
    name: "Most Holy Trinity Monastery (Maronite Monks of Adoration)",
    church_rite: "Maronite Catholic Church (Antiochene Rite)",
    religious_order: "Maronite Monks of Adoration",
    house_type: "Monastery",
    year_founded: 1978,
    is_cloistered: true,
    is_mens_house: true,
    city: "Petersham",
    state_province: "Massachusetts",
    country: "USA",
    address_verified: "67 Wigwam Rd, Petersham, MA 01366",
    website_url: "https://www.maronitemonks.org/",
    vocations_url: "https://www.maronitemonks.org/vocations/",
    contact_person: "Vocation Director",
    contact_email: "monks@maronitemonks.org",
    phone: "(978) 724-3347",
    diocese_eparchy: "Maronite Eparchy of Saint Maron of Brooklyn",
    map_lat_lng: [42.4839, -72.1883],
    notes: "Cloistered Maronite Catholic monks dedicated to perpetual Eucharistic adoration and liturgical prayer in Aramaic/Syriac and English."
  },
  {
    id: "east-holy-protection-pa",
    name: "Holy Protection of the Mother of God Monastery",
    church_rite: "Ruthenian Byzantine Catholic Church",
    religious_order: "Byzantine Carmelite Nuns",
    house_type: "Monastery",
    year_founded: 1957,
    is_cloistered: true,
    is_mens_house: false,
    city: "Sugarloaf",
    state_province: "Pennsylvania",
    country: "USA",
    address_verified: "403 West County Rd, Sugarloaf, PA 18249",
    website_url: "https://www.byzantinediscalcedcarmelites.com/",
    vocations_url: "https://www.byzantinediscalcedcarmelites.com/vocations.html",
    contact_person: "Mother Superior",
    contact_email: "byzantinediscalcedcarmelites@gmail.com",
    phone: "(570) 788-1205",
    diocese_eparchy: "Byzantine Catholic Eparchy of Passaic",
    map_lat_lng: [40.9736, -75.9875],
    notes: "Byzantine Discalced Carmelite nuns combining Carmelite interior prayer with Eastern Christian liturgy."
  },

  // ==========================================
  // APOSTOLIC SISTERS & CONGREGATIONS
  // ==========================================
  {
    id: "sol-annunciation-motherhouse-ny",
    name: "Sisters of Life (Annunciation Motherhouse)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Sisters of Life (SV)",
    house_type: "Motherhouse / Convent",
    year_founded: 1991,
    is_cloistered: false,
    is_mens_house: false,
    city: "Montebello",
    state_province: "New York",
    country: "USA",
    address_verified: "38 Montebello Rd, Suffern, NY 10901",
    website_url: "https://sistersoflife.org/",
    vocations_url: "https://sistersoflife.org/join-us/",
    contact_person: "Vocations Director",
    contact_email: "vocations@sistersoflife.org",
    phone: "(845) 357-3547",
    diocese_eparchy: "Archdiocese of New York",
    map_lat_lng: [41.1347, -74.1378],
    notes: "Founded by Cardinal John O'Connor in 1991. The sisters take a fourth vow to protect and enhance the sacredness of every human life, serving vulnerable pregnant women and hosting healing retreats."
  },
  {
    id: "mc-motherhouse-bronx-ny",
    name: "Missionaries of Charity (US Provincialate)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Missionaries of Charity (MC - Mother Teresa)",
    house_type: "Provincialate / Convent",
    year_founded: 1971,
    is_cloistered: false,
    is_mens_house: false,
    city: "Bronx",
    state_province: "New York",
    country: "USA",
    address_verified: "335 E 145th St, Bronx, NY 10451",
    website_url: "https://www.motherteresa.org/",
    vocations_url: "https://www.motherteresa.org/vocations.html",
    contact_person: "Regional Superior",
    contact_email: "mcbronx@motherteresa.org",
    phone: "(718) 292-0019",
    diocese_eparchy: "Archdiocese of New York",
    map_lat_lng: [40.8144, -73.9233],
    notes: "Founded by Saint Teresa of Calcutta (Mother Teresa) to quench the infinite thirst of Jesus on the Cross by serving the poorest of the poor."
  },
  {
    id: "cfr-sisters-our-lady-of-angels-ny",
    name: "Franciscan Sisters of the Renewal (Our Lady of the Angels Convent)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Franciscan Sisters of the Renewal (CFR)",
    house_type: "Motherhouse / Convent",
    year_founded: 1988,
    is_cloistered: false,
    is_mens_house: false,
    city: "Bronx",
    state_province: "New York",
    country: "USA",
    address_verified: "2314 Tiebout Ave, Bronx, NY 10458",
    website_url: "https://www.franciscansisterscfr.com/",
    vocations_url: "https://www.franciscansisterscfr.com/vocation-inquiry",
    contact_person: "Vocation Directress",
    contact_email: "vocations@franciscansisterscfr.com",
    phone: "(718) 584-0683",
    diocese_eparchy: "Archdiocese of New York",
    map_lat_lng: [40.8572, -73.8967],
    notes: "Apostolic Franciscan community dedicated to Eucharistic adoration, Franciscan simplicity, youth work, and ministering to the poor in the Bronx."
  },
  {
    id: "fs-alton-il",
    name: "Sisters of St. Francis of the Martyr St. George (Motherhouse)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Sisters of St. Francis of the Martyr St. George (FSGM)",
    house_type: "Provincial Motherhouse",
    year_founded: 1923,
    is_cloistered: false,
    is_mens_house: false,
    city: "Alton",
    state_province: "Illinois",
    country: "USA",
    address_verified: "1 Franciscan Way, Alton, IL 62002",
    website_url: "https://altonfranciscans.org/",
    vocations_url: "https://altonfranciscans.org/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "vocations@altonfranciscans.org",
    phone: "(618) 463-2750",
    diocese_eparchy: "Diocese of Springfield in Illinois",
    map_lat_lng: [38.9056, -90.1583],
    notes: "Franciscan sisters dedicated to making the merciful love of Christ visible through healthcare, elder care, and education."
  },
  {
    id: "vhm-georgetown-visitation-dc",
    name: "Georgetown Visitation Monastery",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Order of the Visitation of Holy Mary (VHM - Salesian)",
    house_type: "Monastery",
    year_founded: 1799,
    is_cloistered: true,
    is_mens_house: false,
    city: "Washington",
    state_province: "District of Columbia",
    country: "USA",
    address_verified: "1524 35th St NW, Washington, DC 20007",
    website_url: "https://www.gvmonastery.org/",
    vocations_url: "https://www.gvmonastery.org/vocations",
    contact_person: "Mother Superior",
    contact_email: "monastery@visi.org",
    phone: "(202) 337-3350",
    diocese_eparchy: "Archdiocese of Washington",
    map_lat_lng: [38.9108, -77.0706],
    notes: "Founded in 1799 by Archbishop Leonard Neale and Mother Alice Lalor; historic Georgetown cloister and Georgetown Visitation Preparatory School."
  },
  {
    id: "ssvm-provincialate-dc",
    name: "Servants of the Lord and the Virgin of Matará (SSVM Provincialate)",
    church_rite: "Latin Church (Roman Rite)",
    religious_order: "Servants of the Lord and the Virgin of Matará (SSVM)",
    house_type: "Provincial House",
    year_founded: 1998,
    is_cloistered: false,
    is_mens_house: false,
    city: "Washington",
    state_province: "District of Columbia",
    country: "USA",
    address_verified: "2800 Otis St NE, Washington, DC 20018",
    website_url: "https://ssvmusa.org/",
    vocations_url: "https://ssvmusa.org/index.php/vocations/",
    contact_person: "Vocation Directress",
    contact_email: "vocations.asuncion@servidoras.org",
    phone: "(202) 543-2064",
    diocese_eparchy: "Archdiocese of Washington",
    map_lat_lng: [38.9347, -76.9667],
    notes: "Religious Family of the Incarnate Word (IVE / SSVM); active missionary sisters and cloistered contemplative monasteries."
  }
];

// Write to app/data/monasteries.json and root monasteries.json
const rootPath = path.join(__dirname, '..', 'monasteries.json');
const appDataPath = path.join(__dirname, '..', 'app', 'data', 'monasteries.json');

fs.writeFileSync(rootPath, JSON.stringify(religiousHouses, null, 2), 'utf8');
console.log(`Successfully wrote ${religiousHouses.length} religious houses to ${rootPath}`);

fs.writeFileSync(appDataPath, JSON.stringify(religiousHouses, null, 2), 'utf8');
console.log(`Successfully wrote ${religiousHouses.length} religious houses to ${appDataPath}`);
